src/proj/urls.py
from django.urls import  path
from . import views

app_name='proj'

urlpatterns = [
    path('',views.project_list , name='project_list'),
    path('add',views.add_project , name='add_project'),
    path('<str:slug>',views.project_detail , name = 'project_detail')
]

src/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('contact-us/', include('contact.urls', namespace='contact')),
    path('projects/',include('proj.urls', namespace='projects'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/proj/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
# Create your models here.
PROJECT_TYPE =(('IT','IT'), ('Technology','Technology'), ('Coffe Shops','Coffe Shops'),('Manufacturing','Manufacturing'), ('Media','Media'))

def image_upload(instance,filename):
    imagename,extension = filename.split('.')
    return 'projects/%s.%s'%(instance.id,extension)



class Project(models.Model):  # creates table in database
    owner = models.ForeignKey(User, related_name='project_owner', on_delete=models.CASCADE)
    title= models.CharField(max_length=100)    # creates  column in the table
    description = models.TextField(max_length=1000)
    project_type = models.CharField(max_length=20, choices=PROJECT_TYPE)
    published_at =models.DateTimeField(auto_now=True)
    budget =models.IntegerField(default=0)   # expected Budjet
    image = models.ImageField(upload_to=image_upload)
    location = models.CharField(max_length=100)
    slug = models.SlugField(null=True,blank=True)



    def save(self,*args, **kwargs):
        self.slug = slugify(self.title)
        super(Project,self).save(*args, **kwargs)

    def __str__(self):    # to make object name the title name
        return self.title


class Join(models.Model):
    project = models.ForeignKey(Project, related_name='apply_project', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    webiste = models.URLField()
    cv = models.FileField(upload_to='apply/')
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

src/proj/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from .filters import ProjectFilter
from .models import Project
# Create your views here.
from django.core.paginator import Paginator
from .form import JoinForm , ProjectForm


def project_list(request):

    project_list = Project.objects.all()
    projects_count = project_list.count

    ## filters
    myfilter = ProjectFilter(request.GET,queryset=project_list)
    project_list = myfilter.qs

    paginator = Paginator(project_list , 3)  # Show 5 projects per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={'projects': page_obj ,'count': projects_count , 'myfilter' : myfilter }
    return render(request,'project/project_list.html',context)


def project_detail(request,slug):
    project_detail =  Project.objects.get(slug=slug)

    if request.method == 'POST':
        form = JoinForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.project = project_detail
            myform.save()
            print('DOne')

    else:
        form = JoinForm()

    context = {'project': project_detail, 'form1': form}
    return render(request, 'project/project_detail.html', context)

@login_required
def add_project(request):
    if request.method=='POST':
        form = ProjectForm(request.POST , request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()
            return redirect(reverse('projects:project_list'))

    else:
        form = ProjectForm()

    return render(request,'project/add_project.html',{'form':form})

src/proj/templates/project/add_project.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %} 
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Project</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Post New Project</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}
                                
                                <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock body %}

src/proj/templates/project/project_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{project.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{project.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i>  {{project.location}}</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{project.project_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Project description</h4>
                            <p>{{project.description}}</p>
                             </div>


                    </div>
                     <div class="apply_job_form white-bg">
                        <h4>Apply for Joining Project</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form1 %}
                            {% buttons %}

                                <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Project Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{project.published_at |date:'d M o'}}</span></li>

                                <li>Budget : <span>{{project.budget}}</span></li>
                                <li>Location: <span>{{project.location}}</span></li>
                                <li>Project Field: <span> {{project.project_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }
                              
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

 {% endblock body %}

src/proj/templates/project/project_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{count}}+ Projects Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- Project_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="get">
                                 {% bootstrap_form myfilter.form %}

                                <input type="submit" value="Search" class="boxed-btn3 w-100 mt-2">

                            </form>
                        </div>


                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Projects Listing</h4>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        {% for project in projects %}
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="img/svg_icon/1.svg" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'projects:project_detail' project.slug %}"><h4>{{project.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{project.location}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{project.project_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'projects:project_detail' project.slug %}" class="boxed-btn3">Join</a>
                                        </div>
                                        <div class="date">
                                            <p>Published :{{project.published_at |date:'d M o'}}</p>
                                            <p>Budget :{{project.budget}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                                {% endfor %}
                       {% if projects.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>

                                            {% if projects.has_previous %}
                                                <li><a href="?page={{projects.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                            {% endif %}

                                            {% for i in projects.paginator.page_range %}
                                                <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                            {% endfor %}



                                            {% if projects.has_next %}
                                                <li><a href="?page={{projects.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Project_listing_area_end  -->

{% endblock body %}